
public_keys: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNCdSB6cCYDjDls8Ym9xm5ZKXMn8AmYx5de1BGame/EAH2l/PV5fo11GawaE5B/WKia0zi67JoLhkkXkLkKdaEZS7ZmTvl/VwNCB00301UnDGsc54Oz40hav0ePI9/4lcSEOgjUbqJxPOqOQWBf28/xMqARMWO26bYmZG7RUpssuxCEUnTuxvevBK6ysLcIl13a8hY5HvBuuf3cEpXmxDzXqOtiIqABWzQgjdMjohF2jiUGOXk4qJ5RrSXKC9fA/MmFDtw/0AafNrakbIa0/BSv5E2R9pAJRfKjWMo0B0gQ4iCQtW1sEC/W96TRkHwgaGRl0gO2yPYOlm1wOMk2k6L chibiegg
